### ISSUE TITLE
Crashes on starting

### ISSUE THREAD

**Issue by ViliusN** [thezbyg/gpick#201] opened 2022-05-02 12:28 UTC
[vilius@osmium ~]$ gpick
/usr/include/c++/11.2.0/bits/basic_string.h:1114: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&]: Assertion '!empty()' failed.
Aborted (core dumped)

[vilius@osmium ~]$ sudo pacman -Qi gpick
Name            : gpick
Version         : 0.2.6-4
Description     : Advanced color picker written in C++ using GTK+ toolkit
Architecture    : x86_64
URL             : http://www.gpick.org/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : boost-libs  gtk3  lua
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1141.78 KiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Thu 28 Apr 2022 14:11:36 CEST
Install Date    : Mon 02 May 2022 14:24:33 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by ViliusN** [comment] 2022-05-02 12:29
[vilius@osmium ~]$ gpick -v
Gpick version 0.2.6
Revision unknown
Date 2022-04-28

**Comment by thezbyg** [comment] 2022-05-08 11:48
Hi,
this was fixed in 0e858d33fd28d98d2689d0ebb92c975729a9f7bc. I have released 0.3 version today, but it may take some time for your distribution to update.

As this issue is caused by loading palette file with empty color names, you can workaround by deleting automatic palette save file `/home/USER/.config/gpick/autosave.gpa` and then disabling "Save/Restore palette" in preferences.

**Closed by thezbyg** 2022-05-08 11:48 UTC
